TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devcybaman.db
DATA += devcybaman.proto

#=======================================
include $(TOP)/configure/RULES
